spring.application.name=personal-finance-api

# JPA / Hibernate настройки
# update означает: Hibernate автоматически создаст таблицы в Postgres при запуске, если их еще нет
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Настройки JWT (наш кастомный секретный ключ и время жизни токена)
## Секретный ключ должен быть длинным (не менее 256 бит в кодировке Base64) для алгоритма HMAC-SHA
#app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
## 86400000 миллисекунд = 24 часа
#app.jwt.expiration-ms=86400000
