spring.application.name=personal-finance-api

# PostgreSQL настройки для локального запуска через compose.yaml
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/personal_finance}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:adil}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secretpassword}

# JPA / Hibernate настройки
# update означает: Hibernate автоматически создаст таблицы в Postgres при запуске, если их еще нет
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Настройки JWT (наш кастомный секретный ключ и время жизни токена)
# Секретный ключ должен быть длинным (не менее 256 бит в кодировке Base64) для алгоритма HMAC-SHA
app.jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=}
# 86400000 миллисекунд = 24 часа
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
